name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "00 6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ci_pipe_pssw
          POSTGRES_DB: montrek_ci_pipe_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Clone Montrek Repository
        uses: actions/checkout@master
        with:
          repository: chrishombach/montrek
          token: ${{ secrets.ACCOUNTINGPAT }}
          path: ./montrek
          ref: ${{ vars.MONTREK_BASE_VERSION }}
      - name: Clone mt_economic_common
        uses: actions/checkout@master
        with:
          repository: chrishombach/mt_economic_common
          token: ${{ secrets.ACCOUNTINGPAT }}
          path: ./montrek/montrek/mt_economic_common
          ref: ${{ vars.MT_ECONOMIC_COMMON_BRANCH }}
      - uses: actions/checkout@v3
        with:
          path: ./montrek/montrek/${{ vars.MONTREK_PROJECT }}
      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          cd montrek
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup env
        run: |
          ENVPATH="./montrek/.env"
          echo "DB_ENGINE=postgres" >> $ENVPATH
          echo "DB_PORT=5432" >> $ENVPATH
          echo "DB_USER=postgres" >> $ENVPATH
          echo "DB_PASSWORD=ci_pipe_pssw" >> $ENVPATH
          echo "DB_NAME=montrek_ci_pipe_db" >> $ENVPATH
          echo "DB_HOST=0.0.0.0" >> $ENVPATH
          echo "INSTALLED_APPS=\"mt_tools.excel_processor\"" >> $ENVPATH

      - name: Run Tests and Coverage
        run: |
          cd montrek/montrek
          python manage.py test ${{ vars.MONTREK_PROJECT }} --exclude-tag=functional --parallel
