name: Run Montrek TestSuite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "00 6 * * *"
  workflow_dispatch:

jobs:
  run-tests:
    uses: montrek-software/.github/.github/workflows/montrek_tests_template.yml@main
    with:
      montrek_base_version: ${{ vars.MONTREK_BASE_VERSION }}
      montrek_project: ${{ vars.MONTREK_PROJECT }}
      mt_cloud_ref: ""
      mt_economic_common_ref: ""
    secrets:
      PAT: ${{ secrets.ACCOUNTINGPAT }}
