name: Run Montrek Release-Drafter
on:
  push:
    branches:
      - main # <- change if your default branch is different
    tags:
      - "v*" # when you push a tag like v1.2.3 we'll publish
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]
  workflow_dispatch:
jobs:
  run-tests:
    uses: montrek-software/montrek-templates/.github/workflows/montrek_release_drafter_template.yml@main
